liquibase.command.url=jdbc:sqlserver://localhost:1433;databaseName=PatientManagementDB;encrypt=true;trustServerCertificate=true;sendTimeAsDatetime=false
liquibase.command.username=patientapp
liquibase.command.password=Patient@123
liquibase.command.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
liquibase.command.classpath=liquibase-lib/mssql-jdbc-13.4.0.jre11.jar