spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:sqlserver://${DB_SERVER}:${DB_PORT};databaseName=${DB_NAME};encrypt=true;trustServerCertificate=true;sendTimeAsDatetime=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-app-master.yaml

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 12MB
      file-size-threshold: 0B