url=jdbc:sqlserver://localhost:1433;databaseName=PatientManagementDB;encrypt=true;trustServerCertificate=true;sendTimeAsDatetime=false

username=patientapp

password=Patient@123

driver=com.microsoft.sqlserver.jdbc.SQLServerDriver

changeLogFile=db/changelog/db.changelog-master.yaml